### ISSUE TITLE
FEATURE: Handle absent students

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/popsicle-sticks-extension#3]
## Feature request
> The last suggestion that would be a help but may also be a tricky feature to implement, would be a way of dealing with absent students. The easiest way would just be to ignore their name and keep going. But I wondered if it would be valuable to have an "absent" button next to the "remove" button for students, to toggle them on and off for including in the randomization. That would be better than deleting them and re-entering them later, but I guess either isn't really that necessary if their name can simply be ignored that day.

## Possible solutions
- [ ] Take "attendance" on class view
- [ ] Remove students from list when they come up

## Considerations
- Time sensitive: marking a student absent should only be saved for one day

## Tasks
- [ ] Decide on approach

**Comment by SeanMcP** [comment]
I've decided that this is a non-issue for now. We can reevaluate this in a later release.
