### ISSUE TITLE
FEATURE: Clone class

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/popsicle-sticks-extension#4]
## Description

> Add a button on the class view to clone the current class and students with a new name

## Tasks
- [ ] Create clone view
- [ ] Load existing classes
- [ ] Add clone to store based on source

**Comment by SeanMcP** [comment]
🤦‍♀️ This feature already exists. I'm an egg.
