### ISSUE TITLE
SPIKE: Download, upload data

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/popsicle-sticks-extension#8]
## Description

> Provide users the ability to download and upload student data that will be pushed straight to the store.

## Tasks
- [ ] Create a new screen
- [ ] Trigger download from store
- [ ] Upload JSON file into store
